In [1]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import confusion_matrix

In [5]:
df = pd.read_csv('/content/winequality.csv')

In [6]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.3,0.70,0.00,1.90,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.60,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.30,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.90,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.2,0.70,0.00,1.90,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1994,9.0,0.45,0.12,15.92,0.049,67.0,62.0,0.99520,2.75,0.49,9.9,9
1995,10.0,0.78,0.10,12.15,0.017,37.0,37.0,0.99579,2.46,1.22,12.6,2
1996,11.0,0.74,0.14,8.12,0.026,52.0,18.0,0.99897,3.49,0.92,9.4,7
1997,15.0,0.62,0.19,1.81,0.027,17.0,54.0,0.99471,2.67,0.76,8.6,6
1998,5.0,0.43,0.13,5.11,0.048,64.0,149.0,0.99607,3.30,0.46,9.0,7

In [7]:
le = {}
df_enc = df.copy()
for col in df_enc.columns:
    le[col] = LabelEncoder()
    df_enc[col] = le[col].fit_transform(df_enc[col])
df_enc

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,26,77,0,32,66,11,28,463,112,22,13,3
1,31,113,0,57,88,25,61,386,81,34,19,3
2,31,89,4,47,82,15,48,402,87,31,19,3
3,65,13,56,32,65,17,54,478,77,24,19,4
4,25,77,0,32,66,11,28,463,112,22,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1994,43,36,12,421,39,69,56,242,36,15,20,7
1995,53,93,10,331,7,37,31,295,12,87,53,0
1996,63,85,14,239,16,54,12,533,110,58,13,5
1997,92,61,19,27,17,17,48,202,29,42,2,4
1998,3,34,13,150,38,66,144,319,91,12,6,5